#################
### Oh my zsh ###
#################

export ZSH="$HOME/.oh-my-zsh"
ZSH_THEME="" # no theme
plugins=(
	git
	colored-man-pages
)
source "$ZSH/oh-my-zsh.sh"

###################
### Environment ###
###################

export HISTSIZE=5000
export SAVEHIST=5000
export PAGER=less
export EDITOR=nvim
export VISUAL=nvim

#############
### Paths ###
#############

# Java
export JAVA_HOME="/opt/java/latest"
export PATH="$JAVA_HOME/bin:$PATH"

# Maven
export MAVEN_HOME="/opt/maven/latest"
export PATH="$MAVEN_HOME/bin:$PATH"

# Personal scripts
export PATH="$HOME/.local/bin:$PATH"

# Go
export PATH="/opt/go/bin:$PATH"

# Neovim
export PATH="/opt/nvim/bin:$PATH"

# Latex
export PATH="/usr/local/texlive/2026/bin/x86_64-linux:$PATH"

# Racket
export PATH="/opt/racket/bin:$PATH"

# Node
export PATH="/opt/node/bin:$PATH"

###############
### Aliases ###
###############

alias grep='grep --color=auto'
alias ls='ls -p --color=auto'

command -v batcat &> /dev/null && alias bat='batcat --pager=cat'

###########################
### Load external files ###
###########################

# Load aliases
[[ -f "$HOME/.aliases" ]] && source "$HOME/.aliases"

##################
### Oh my posh ###
##################

theme='custom'
eval "$(oh-my-posh init zsh --config "$HOME/.omp-themes/$theme.omp.json")"

#################
### Fastfetch ###
#################

fastfetch

