# If not running interactively, don't do anything
[[ $- != *i* ]] && return

###################
### Environment ###
###################

export HISTSIZE=5000 # history size
export HISTFILESIZE=5000
export HISTCONTROL=ignoreboth
export PAGER=less
export EDITOR=nvim
export VISUAL=nvim
export GREP_COLORS='ms=1;31' # grep colors (red)

export GROFF_NO_SGR=1

# Colored man pages
export LESS_TERMCAP_mb=$'\e[1;31m'     # begin blinking (red)
export LESS_TERMCAP_md=$'\e[1;31m'     # begin bold (headings/titles in red)
export LESS_TERMCAP_me=$'\e[0m'        # end bold/blink
export LESS_TERMCAP_se=$'\e[0m'        # end standout mode
export LESS_TERMCAP_so=$'\e[01;33;44m' # begin standout (status bar: yellow on blue)
export LESS_TERMCAP_ue=$'\e[0m'        # end underline
export LESS_TERMCAP_us=$'\e[01;32m'    # begin underline (green)

#############
### Paths ###
#############

# Java
export JAVA_HOME="/opt/java/latest"
export PATH="$JAVA_HOME/bin:$PATH"

# Maven
export MAVEN_HOME="/opt/maven/latest"
export PATH="$MAVEN_HOME/bin:$PATH"

# Personal scripts
export PATH="$HOME/.local/bin:$PATH"

# Go
export PATH="/opt/go/bin:$PATH"

# Neovim
export PATH="/opt/nvim/bin:$PATH"

# Latex
export PATH="/usr/local/texlive/2026/bin/x86_64-linux:$PATH"

# Racket
export PATH="/opt/racket/bin:$PATH"

#####################
### Shell options ###
#####################

shopt -s histappend   # append to command history
shopt -s cdspell      # correct spelling errors when using cd
shopt -s checkwinsize # update terminal dimensions after each command
shopt -s dirspell     # correct directory spelling errors during completion (tab)
shopt -s autocd       # change directory without using cd

###############
### Aliases ###
###############

alias grep='grep --color=auto'
alias ls='ls -p --color=auto'

command -v batcat &>/dev/null && alias bat='batcat --pager=cat'

##############
### Prompt ###
##############

# <user>@<hostname> <cwd> $

# User
PS1='\[\e[38;5;81m\]\u@\[\e[0m\]'

# Hostname
PS1+='\[\e[38;5;81m\]\h\[\e[0m\] '

# pwd
PS1+='\[\e[38;5;157m\]\w\[\e[0m\] '

# Prompt character
PS1+='\[\e[38;5;81m\]\$\[\e[0m\] '

###########################
### Load external files ###
###########################

# Load aliases
[[ -f "$HOME/.aliases" ]] && source "$HOME/.aliases"

# Load completion
if [[ -f "/usr/share/bash-completion/bash_completion" ]]; then
	source "/usr/share/bash-completion/bash_completion"
elif [[ -f "/etc/bash_completion" ]]; then
	source "/etc/bash_completion"
fi

##################
### Oh my posh ###
##################

theme='robbyrussell'
eval "$(oh-my-posh init bash --config "$HOME/.omp-themes/$theme.omp.json")"

#################
### Fastfetch ###
#################

fastfetch
